version: '3.4'

services:
  registery:
    build:
      context: ./registery
    ports:
      - "8761:8761"
    healthcheck:
      test: ["CMD", "wget" , "-f", "http://localhost:8761"]

  config-server:
    build: 
      context: ./config-server
    ports:
      - "9999:9999"
    depends_on: 
      - registery
    environment: 
      eureka_host: registery
    healthcheck:
      test: wget --no-verbose --tries=1 --spider http://localhost:9999/actuator/info/ || exit 1
      interval: 3s
      timeout: 5s
      start_period: 2s

  config-client:
    build: 
      context: ./config-client
    ports: 
      - "8080:8080"
    depends_on: 
      config-server:
        condition: service_healthy
      registery:
        condition: service_started
    environment: 
      eureka_host: registery
    healthcheck:
      test: ["CMD", "wget" , "-f", "http://localhost:8080"]