spring:
  application:
    name: config-client
  config:
    import: configserver:http://localhost:9999
  profiles:
    active: development
  cloud:
    config:
      label: master
      profile: development
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    fetch-registry: true
  instance:
    prefer-ip-address: true